export const WhetherOrNot = { yes: '是', no: '否' };
export const TechnicalSide = { backend: '后端', front: '前端', frontBackend: '前后端' };
export const ZentaoPhase = {
  1: '未开始',
  2: '开发中',
  3: '开发完',
  4: '已提测',
  5: '测试中',
  6: 'TE测试环境已验过',
  7: 'UED测试环境已验过',
  8: '已取消',
  9: '开发已revert',
  10: '测试已验证revert',
  11: '灰度已验过',
  12: '线上已验过',
};
export const ZentaoType = { bug: 'Bug', story: 'Story', B_story: 'B_Story', task: 'Task' };
export const ZentaoStatus = {
  active: '激活',
  closed: '已关闭',
  verified: '已验证',
  resolved: '已解决',
  wait: '未开始',
  doing: '进行中',
  done: '已完成',
  pause: '已暂停',
  cancel: '已取消',
  changed: '已更改',
  draft: '已草拟',
};
export const CheckStatus = {
  skip: { text: '忽略', color: '#bfbfbf' },
  yes: { text: '通过', color: '#52c41a' },
  no: { text: '不通过', color: '#ff4d4f' },
  noHot: { text: '不可热更', color: '#d46b08' },
  version: { text: '未封板', color: '#faad14' },
  wait: { text: '未开始' },
  running: { text: '执行中', color: '#1890ff' },
};
export const checkInfo = [
  {
    check_type: '前端单元测试运行是否通过',
    side: '前端',
    status: 'yes',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'front_unit',
    disabled: false,
  },
  {
    check_type: '前端图标一致性检查是否通过',
    side: '前端',
    status: 'no',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'front_icon',
    disabled: false,
  },
  {
    check_type: '前端代码遗漏检查是否通过',
    side: '前端',
    status: 'running',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'front_code',
    disabled: false,
  },
  {
    check_type: '前端服务git分支是否封板',
    side: '前端',
    status: 'wait',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'front_branch',
    disabled: false,
  },
  {
    check_type: '后端单元测试运行是否通过',
    side: '后端',
    status: 'noHot',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'backend_unit',
    disabled: false,
  },
  {
    check_type: '后端代码遗漏检查是否通过',
    side: '后端',
    status: 'skip',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'backend_code',
    disabled: false,
  },
  {
    check_type: '创建库对比校验是否通过',
    side: '后端',
    status: 'version',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'access',
    disabled: false,
  },
  {
    check_type: '后端环境一致性检查是否通过',
    side: '后端',
    status: '',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'env',
    disabled: false,
  },
  {
    check_type: '后端是否可以热更新',
    side: '后端',
    status: '',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'hot_check',
    disabled: false,
  },
  {
    check_type: '后端服务git分支是否封板',
    side: '后端',
    status: '',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'backend_branch',
    disabled: false,
  },
  {
    check_type: '上线前检查checklist是否检查完成',
    side: '公共',
    status: '',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'checkList',
    disabled: false,
  },
  {
    check_type: '需求阶段是否满足条件（需要测试需达到测试完毕/无需测试需要开发完毕）',
    side: '公共',
    status: '',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'stage',
  },
  {
    check_type: 'previewsql是否已执行',
    side: '公共',
    status: '',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'previewsql',
    disabled: false,
  },
  {
    check_type: 'web/h5部署时是否勾选自动化测试参数',
    side: '公共',
    status: '',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'auto_test',
    disabled: false,
  },
  {
    check_type: '升级前自动化检查是否通过',
    side: '测试',
    status: '',
    start: '',
    end: '',
    open: false,
    open_pm: '',
    open_time: '',
    log: '',
    rowKey: 'auto_check',
    disabled: false,
  },
];
